---
title: "Вот написал такой я скрипт"
author: "В. М. Хайтов"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


Результаты нашей работы

```{r}
sleep <- read.table('data/sleep.csv', header = TRUE, sep = '\t')


sleep$Danger <- factor(sleep$Danger, levels = 1:5, labels = c('очень низкий', 'низкий', 'средний', 'высокий', 'очень высокий'))


sl <- sleep[!is.na(sleep$TotalSleep), ]

library(dplyr)

sl <- 
sleep %>% 
  filter(!is.na(TotalSleep))



library(ggplot2)

ggplot(sl, aes(x = Danger, y = TotalSleep)) +
  geom_point()


sl_anova <- aov(TotalSleep ~ Danger, data = sl)


summary(sl_anova)

sl_diag <- fortify(sl_anova)


ggplot(sl_diag, aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0)


ggplot(data = sl_diag, aes(x = Danger, y = .resid)) + geom_boxplot() + geom_hline(yintercept = 0)


library(car)
qqPlot(sl$TotalSleep)

qqPlot(sl_diag$.resid)

TukeyHSD(sl_anova)


Pl_sl <-
  sl %>% 
  group_by(Danger) %>% 
  summarise(Mean = mean(TotalSleep),
            Sd = sd(TotalSleep),
            n = n(),
            SE = Sd/sqrt(n),
            CI_low = Mean - qt(p = 0.975, df = n - 1) * SE,
            CI_up = Mean + qt(p = 0.975, df = n - 1) * SE) %>% 
  ggplot(aes(x = Danger, y = Mean)) +
  geom_col(fill = "gray") +
  geom_errorbar(aes(ymin = CI_low, ymax = CI_up), width = 0.2)

  
  Pl_sl +
    geom_segment(aes(y = 16.6, yend = 16.6, x = "очень высокий", xend = "очень низкий")) +
    geom_segment(aes(y = 16.4, yend = 16.4, x = "очень высокий", xend = "низкий")) +
    geom_segment(aes(y = 16.2, yend = 16.2, x = "очень высокий", xend = "средний"))



```

