---
title: Проекты к зачёту
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    theme: flatly
    highlight: haddock
    include:
      after_body: _footer.html
    css: page_styles.css
---

## Проекты

### Описание 

Проекты небольшие и рассчитаны на выполнение в группе из двух человек. В ходе работы вам нужно будет опробовать методы, о которых мы говорили в курсе, и подобрать для каждого датасета оптимальный способ анализа данных и его представления. 

Отчёт по проекту будет состоять из двух частей: письменной (выполненная в формате `.Rmd`) и устной (презентация на 10 минут). В письменном файле должны обязательно содержаться куски выполненного кода (следите за грамотным его оформлением!) и краткое описание того, что вы делали, зачем и что получили. Результаты анализа должны быть представлены как с указанием необходимых для интепретации результатов статистик, так и с использованием репрезентативных визуализацией. В ходе рассказки презентации будет оцениваться ваше умение представить полученные данные и обоснование выбранного вами подхода (+ умение отвечать на вопросы). 

### Проект №1. Цыплята и кормовые добавки

Данные эксперимента по сравнению эффективности влияния различных пищевых добавок на рост цыплят. 

[Данные](projects/project_1/project1.csv).

Описание:
- weight --- вес цыплят
- feed - пищевая добавка. Фактор с уровнями:
          "casein" (казеин),
          "horsebean" (бобы),
          "linseed" (льняное семя),
          "meatmeal" (мясо-костная мука),
          "soybean" (соевые бобы),
          "sunflower" (семена подсолнечника).


### Проект №2. Покемоны

Датасет содержит информацию о всех 802 покемонах, а также его многочисленные характеристики. 

[Данные](projects/project_2/project2.csv)
[Описание данных](projects/project_2/summary2.csv)

Данные взяты из проекта на [Kaggle](https://www.kaggle.com/datasets/rounakbanik/pokemon). 

### Проект №3. Бабочки мигрируют, бабочки остаются

Исследование мигрирующих и "осёдлых" бабочек, и как образ жизни влияет на паразитов бабочек. Датасет также содержит информацию о стабильных изотопах, что в оригинальном исследовании позволило определить, откуда собранные бабочки родом. 

[Данные](projects/project_3/project3.csv).
[Описание данных](projects/project_3/summary3.xlsx).

[Оригинальная статья](projects/project_3/publ3.pdf)


### Проект №4. Моллюски и симбионты

Данные о симбионтах двустворчатых моллюсков, собранные за 10 лет.  

- [Данные](projects/project_4/project4.xlsx). 
- [Описание](projects/project_4/summary_4.xlsx). 

Данные любезно предоставлены В.А. Крапивиным.

### Проект №5. Винишко

Данные о качестве вина и его физико-химических характеристиках. 

Исходные данные разделены на [красные](projects/project_5/project5_red.csv) и [белые](projects/project_5/project5_white.csv) вина. 
[Описание данных](projects/project_5/summary5.csv). 

[Оригинальная статья](projects/project_5/publication.pdf).

### Проект №6. Черепахи и  их черепа

Морфометрия черепов черепах. 24 разных измерения черепов черепах 122 ныне живущих пресноводных, морских и наземных видов и одного ископаемого. 

Environment3: 0 --- Freshwater, 1 --- Terrestrial, 2 --- Marine, 9 --- Fossil.

[Картинка с измерениями](images/Fig30.1ZuurAED-mod.jpg)

[Данные](projects/project_6/project6.txt).


### Проект №7 (со звёздочкой!)

Данные о регенерации *Platynereis dumerilii* (Pdum) и *Pygospio elegans* (Pele) и экспрессии различных генов. 

[Данные по *P. dumerilli*](projects/project_7/project7_pdum.tsv).
[Данные по *P. elegans*](projects/project_7/project7_pele.tsv).

Описание:
- Ref_ID --- порядковый номер сиквенса;
- Annotations --- аннотация последовательности.

Экспрессию генов смотрели в голове и xвосте через определённое количество времени (0, 4, 12, 24, 48 и 96 часов). Каждой стадии соотносится две реплики. Данные частично взяты из [проекта](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA901144). Экспрессия измерена в TPM (transcript per million). 
